---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/content/test
  label: Teset
  create: all
  match: "**/*"
- type: directory
  path: src/content/posts
  label: News
  create: documents
  match: "**/*"
  templates:
  - news
upload_dir: src/content
public_path: src/content
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
